package router

import (
	"pubcore/controllers"
	"pubcore/middlewares"
	"strings"
	"time"

	"github.com/gin-contrib/cors"
	"github.com/gin-gonic/gin"

	_ "pubcore/docs" // docs is generated by Swag CLI, you have to import it.

	ginSwagger "github.com/swaggo/gin-swagger"

	swaggerfiles "github.com/swaggo/files"
)

// StartServer configures and returns the Gin engine with all routes.
func StartServer() *gin.Engine {
	r := gin.Default()

	// 1. CORS Configuration (Should be first to handle preflight requests correctly)
	config := cors.Config{
		AllowOriginFunc: func(origin string) bool {
			return true // Allow all origins in development
		},
		AllowMethods:     []string{"GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS"},
		AllowHeaders:     []string{"Origin", "Content-Type", "Accept", "Authorization", "X-Requested-With", "Access-Control-Allow-Origin", "X-CSRF-Token", "Referer", "User-Agent"},
		ExposeHeaders:    []string{"Content-Length", "Access-Control-Allow-Origin", "Access-Control-Allow-Credentials"},
		AllowCredentials: true,
		MaxAge:           12 * time.Hour,
	}

	r.Use(cors.New(config))

	// 2. Disable automatic redirects to prevent CORS issues with trailing slashes
	r.RedirectTrailingSlash = false
	r.RedirectFixedPath = false

	// 3. Middleware to normalize paths (strip trailing slashes internally)
	r.Use(func(c *gin.Context) {
		path := c.Request.URL.Path
		if path != "/" && strings.HasSuffix(path, "/") {
			c.Request.URL.Path = strings.TrimSuffix(path, "/")
		}
		c.Next()
	})

	// Auth Routes (public)
	authRouter := r.Group("/auth")
	{
		authRouter.POST("/register", controllers.UserRegister)
		authRouter.POST("/login", controllers.UserLogin)
		authRouter.POST("/logout", middlewares.Authentication(), controllers.UserLogout)
	}

	// Authors Routes (protected)
	authorRouter := r.Group("/authors")
	{
		authorRouter.Use(middlewares.Authentication())
		authorRouter.GET("", controllers.GetAuthors)
		authorRouter.GET("/", controllers.GetAuthors)
		authorRouter.GET("/:id", controllers.GetAuthorByID)
		authorRouter.POST("", controllers.CreateAuthor)
		authorRouter.POST("/", controllers.CreateAuthor)
		authorRouter.PUT("/:id", controllers.UpdateAuthor)
		authorRouter.DELETE("/:id", controllers.DeleteAuthor)
	}

	// Publishers Routes (protected)
	publisherRouter := r.Group("/publishers")
	{
		publisherRouter.Use(middlewares.Authentication())
		publisherRouter.GET("", controllers.GetPublishers)
		publisherRouter.GET("/", controllers.GetPublishers)
		publisherRouter.GET("/:id", controllers.GetPublisherByID)
		publisherRouter.POST("", controllers.CreatePublisher)
		publisherRouter.POST("/", controllers.CreatePublisher)
		publisherRouter.PUT("/:id", controllers.UpdatePublisher)
		publisherRouter.DELETE("/:id", controllers.DeletePublisher)
	}

	// Books Routes (protected)
	bookRouter := r.Group("/books")
	{
		bookRouter.Use(middlewares.Authentication())
		bookRouter.GET("", controllers.GetBooks)
		bookRouter.GET("/", controllers.GetBooks)
		bookRouter.GET("/:id", controllers.GetBookByID)
		bookRouter.POST("", controllers.CreateBook)
		bookRouter.POST("/", controllers.CreateBook)
		bookRouter.PUT("/:id", controllers.UpdateBook)
		bookRouter.DELETE("/:id", controllers.DeleteBook)
	}

	// Swagger UI
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerfiles.Handler))

	return r
}
